[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  bblanchon/ArduinoJson
  paulstoffregen/OneWire
  milesburton/DallasTemperature

build_flags =
  -D ARDUINOJSON_USE_LONG_LONG=1
